# Generated by Django 3.1.6 on 2021-02-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothing',
            name='isChild',
        ),
        migrations.AddField(
            model_name='clothing',
            name='forChild',
            field=models.BooleanField(default=False, verbose_name='for child'),
        ),
        migrations.AddField(
            model_name='clothing',
            name='sex',
            field=models.IntegerField(choices=[(None, '(Unknown)'), (0, 'male'), (1, 'female'), (2, 'unisex')], default=2, verbose_name='sex'),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='_type',
            field=models.CharField(choices=[('JACKET', 'Jacket'), ('COAT', 'Coat'), ('HOODY', 'Hoody'), ('T_SHIRT', 'T-shirt'), ('SHIRT', 'Shirt'), ('PANTS', 'Pants'), ('DENIM', 'Denim'), ('SNEAKERS', 'Sneakers'), ('BOOTS', 'Boots'), ('UNDERWEAR', 'Underwear'), ('ACCESSORIES', 'Accessories'), ('DEFAULT', 'Other')], default='DEFAULT', max_length=12, verbose_name='type of clothes'),
        ),
    ]
